version: '3'

services:
  template-django:
    container_name: template-django
    build:
      context: .
      dockerfile: Dockerfile
    image: template-django
    volumes:
      - .:/home/app/service:rw
    ports:
      - 8000:8000
    environment:
      - VAULT_TOKEN=$VAULT_TOKEN
      - ENV=stg
      - VAULT_HOST=$VAULT_HOST
    depends_on:
    - db
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=frexco
      - POSTGRES_HOST=db